"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Task={id:string;subject:string;topic:string;minutes:number;priority:"high"|"medium"|"low";done:boolean};
const starter:Task[]=[
{id:"p1",subject:"Physics",topic:"Kinematics practice",minutes:35,priority:"high",done:false},
{id:"c1",subject:"Chemistry",topic:"Mole concept revision",minutes:30,priority:"high",done:false},
{id:"m1",subject:"Mathematics",topic:"Quadratic equations",minutes:25,priority:"medium",done:false},
{id:"b1",subject:"Biology",topic:"Cell structure flashcards",minutes:20,priority:"low",done:false}
];

export default function AdaptiveStudy(){
 const[tasks,setTasks]=useState<Task[]>(starter),[energy,setEnergy]=useState(6),[available,setAvailable]=useState(90),[examDays,setExamDays]=useState(12),[subject,setSubject]=useState(""),[topic,setTopic]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState("Missing a session is data, not failure."),[focusId,setFocusId]=useState<string|null>(null),[seconds,setSeconds]=useState(25*60),[running,setRunning]=useState(false),[studyDates,setStudyDates]=useState<string[]>([]);
 useEffect(()=>{try{const saved=localStorage.getItem("njacp-adaptive-study");if(saved){const d=JSON.parse(saved);if(Array.isArray(d.tasks))setTasks(d.tasks);if(typeof d.energy==="number")setEnergy(d.energy);if(typeof d.available==="number")setAvailable(d.available);if(typeof d.examDays==="number")setExamDays(d.examDays);if(Array.isArray(d.studyDates))setStudyDates(d.studyDates);}}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem("njacp-adaptive-study",JSON.stringify({tasks,energy,available,examDays,studyDates}));}catch{}},[tasks,energy,available,examDays]);
 const ordered=useMemo(()=>{const r={high:3,medium:2,low:1};return [...tasks].sort((a,b)=>Number(a.done)-Number(b.done)||r[b.priority]-r[a.priority])},[tasks]);
 const done=tasks.filter(t=>t.done).length,progress=tasks.length?Math.round(done/tasks.length*100):0; const streak=(()=>{let n=0;const set=new Set(studyDates);const d=new Date();while(set.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n})();
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(timer);setRunning(false);setMessage("Focus session complete. Take a short break, then mark the task done if you finished it.");return 0}return s-1}),1000);return()=>clearInterval(timer)},[running]);
 function startFocus(id:string){setFocusId(id);setSeconds(25*60);setRunning(true);setMessage("25-minute focus session started. One task at a time.");}
 function resetFocus(){setRunning(false);setSeconds(25*60);setFocusId(null);} function reason(t:Task){if(t.done)return "Completed";if(t.priority==="high"&&examDays<=7)return "High priority + exam soon";if(energy<=3)return "Shortened because energy is low";if(t.priority==="high")return "High-priority topic";return "Fits your current study capacity";}
 function revisionAdvice(){const open=tasks.filter(t=>!t.done);if(!open.length)return "Everything in the current queue is complete. Use the time for light review or rest.";const urgent=open.filter(t=>t.priority==="high").sort((a,b)=>a.minutes-b.minutes)[0];if(urgent)return "Revise "+urgent.subject+" · "+urgent.topic+" next. It is high priority and "+(examDays<=7?"your exam is close.":"should stay near the top of the queue.");return "Revise "+open.sort((a,b)=>a.minutes-b.minutes)[0].topic+" next because it is the smallest unfinished block and is easy to complete today.";}
 function toggle(id:string){setTasks(x=>x.map(t=>t.id===id?{...t,done:!t.done}:t));const today=new Date().toISOString().slice(0,10);setStudyDates(x=>x.includes(today)?x:[...x,today]);setMessage("Nice. NJACP will use that change when you adapt the plan.");}
 function add(e:FormEvent){e.preventDefault();if(!subject.trim()||!topic.trim())return;setTasks(x=>[...x,{id:crypto.randomUUID(),subject:subject.trim(),topic:topic.trim(),minutes:energy<=3?15:25,priority:"medium",done:false}]);setSubject("");setTopic("");}
 async function adapt(){setLoading(true);try{const r=await fetch("/api/study-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tasks,energy,available,examDays})});const d=await r.json();if(Array.isArray(d.tasks))setTasks(d.tasks);setMessage(d.explanation||"Plan adapted.");}catch{setMessage("The local planner adapted your queue without needing the AI model.");}finally{setLoading(false)}}
 return <main className="min-h-screen bg-[#f6f7fb] text-slate-900"><header className="mx-auto flex max-w-6xl items-center justify-between px-4 py-5"><a href="/" className="font-black">← NJACP</a><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">Adaptive Study</span></header>
 <section className="mx-auto max-w-6xl px-4 pb-12"><div className="rounded-[2rem] bg-slate-950 p-7 text-white md:p-10"><p className="font-bold text-indigo-300">NJACP Adaptive Study Companion</p><h1 className="mt-3 max-w-3xl text-4xl font-black md:text-6xl">A study plan that adapts when real life happens.</h1><p className="mt-4 max-w-2xl leading-7 text-slate-300">Use energy, available time and exam proximity to rebuild a realistic plan instead of punishing yourself for missing one.</p></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.4fr]"><div className="space-y-5"><div className="rounded-3xl border bg-white p-6 shadow-sm"><b>Today’s reality</b><label className="mt-5 block text-sm font-semibold">Energy: {energy}/10</label><input type="range" min="1" max="10" value={energy} onChange={e=>setEnergy(+e.target.value)} className="mt-3 w-full"/><label className="mt-5 block text-sm font-semibold">Available: {available} min</label><input type="range" min="15" max="240" step="15" value={available} onChange={e=>setAvailable(+e.target.value)} className="mt-3 w-full"/><label className="mt-5 block text-sm font-semibold">Exam: {examDays} days</label><input type="range" min="1" max="60" value={examDays} onChange={e=>setExamDays(+e.target.value)} className="mt-3 w-full"/><button onClick={adapt} disabled={loading} className="mt-6 w-full rounded-2xl bg-indigo-600 py-3 font-bold text-white">{loading?"Adapting…":"Adapt my plan"}</button><p className="mt-4 rounded-2xl bg-indigo-50 p-4 text-sm leading-6 text-indigo-900">{message}</p></div><div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex justify-between"><b>Progress</b><b className="text-indigo-600">{progress}%</b></div><div className="mt-4 rounded-2xl bg-amber-50 p-4"><b>{streak}-day study streak</b><p className="mt-1 text-sm text-slate-600">Consistency is built one session at a time.</p></div><div className="mt-3 rounded-2xl bg-violet-50 p-4"><b>AI revision recommendation</b><p className="mt-1 text-sm leading-6 text-violet-950">{revisionAdvice()}</p><p className="mt-2 text-xs text-violet-700">Recommendation uses your current queue, priority and exam proximity.</p></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-indigo-600" style={{width:progress+"%"}}/></div><p className="mt-3 text-sm text-slate-500">{done} completed • {tasks.filter(t=>!t.done).reduce((n,t)=>n+t.minutes,0)} planned minutes remaining</p></div></div>
 <div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="font-black">Adaptive queue</div><div className="mt-5 space-y-3">{ordered.map(t=><div key={t.id} className={"flex w-full items-center gap-3 rounded-2xl border p-4 "+(t.done?"bg-emerald-50":"")}><button onClick={()=>toggle(t.id)} className="grid h-8 w-8 shrink-0 place-items-center rounded-full border font-black">{t.done?"✓":""}</button><span className="min-w-0 flex-1 text-left"><b className={t.done?"line-through":""}>{t.subject} · {t.topic}</b><small className="mt-1 block text-slate-500">{t.minutes} min · {t.priority} priority · {reason(t)}</small></span>{!t.done&&<button onClick={()=>startFocus(t.id)} className="rounded-xl bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Focus</button>}</div>)}</div>{focusId&&<div className="mt-5 rounded-2xl bg-slate-950 p-5 text-white"><div className="text-sm text-slate-300">Focus session</div><div className="mt-1 font-bold">{tasks.find(t=>t.id===focusId)?.topic||"Selected task"}</div><div className="my-4 text-5xl font-black tabular-nums">{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</div><div className="flex gap-2"><button onClick={()=>setRunning(!running)} className="rounded-xl bg-indigo-500 px-4 py-2 text-sm font-bold">{running?"Pause":"Resume"}</button><button onClick={resetFocus} className="rounded-xl bg-white/10 px-4 py-2 text-sm font-bold">Reset</button></div></div>}<form onSubmit={add} className="mt-5 grid gap-2 sm:grid-cols-[.7fr_1.3fr_auto]"><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject" className="rounded-xl bg-slate-100 px-3 py-3 text-sm"/><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Topic or task" className="rounded-xl bg-slate-100 px-3 py-3 text-sm"/><button className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Add</button></form></div></div></section></main>
}