"use client";

import { FormEvent, useMemo, useState } from "react";

type Task={id:string;subject:string;topic:string;minutes:number;priority:"high"|"medium"|"low";done:boolean};
const starter:Task[]=[
{id:"p1",subject:"Physics",topic:"Kinematics practice",minutes:35,priority:"high",done:false},
{id:"c1",subject:"Chemistry",topic:"Mole concept revision",minutes:30,priority:"high",done:false},
{id:"m1",subject:"Mathematics",topic:"Quadratic equations",minutes:25,priority:"medium",done:false},
{id:"b1",subject:"Biology",topic:"Cell structure flashcards",minutes:20,priority:"low",done:false}
];

export default function AdaptiveStudy(){
 const[tasks,setTasks]=useState<Task[]>(starter),[energy,setEnergy]=useState(6),[available,setAvailable]=useState(90),[examDays,setExamDays]=useState(12),[subject,setSubject]=useState(""),[topic,setTopic]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState("Missing a session is data, not failure.");
 const ordered=useMemo(()=>{const r={high:3,medium:2,low:1};return [...tasks].sort((a,b)=>Number(a.done)-Number(b.done)||r[b.priority]-r[a.priority])},[tasks]);
 const done=tasks.filter(t=>t.done).length,progress=tasks.length?Math.round(done/tasks.length*100):0;
 function toggle(id:string){setTasks(x=>x.map(t=>t.id===id?{...t,done:!t.done}:t));setMessage("Nice. NJACP will use that change when you adapt the plan.");}
 function add(e:FormEvent){e.preventDefault();if(!subject.trim()||!topic.trim())return;setTasks(x=>[...x,{id:crypto.randomUUID(),subject:subject.trim(),topic:topic.trim(),minutes:energy<=3?15:25,priority:"medium",done:false}]);setSubject("");setTopic("");}
 async function adapt(){setLoading(true);try{const r=await fetch("/api/study-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tasks,energy,available,examDays})});const d=await r.json();if(Array.isArray(d.tasks))setTasks(d.tasks);setMessage(d.explanation||"Plan adapted.");}catch{setMessage("The local planner adapted your queue without needing the AI model.");}finally{setLoading(false)}}
 return <main className="min-h-screen bg-[#f6f7fb] text-slate-900"><header className="mx-auto flex max-w-6xl items-center justify-between px-4 py-5"><a href="/" className="font-black">← NJACP</a><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">Adaptive Study</span></header>
 <section className="mx-auto max-w-6xl px-4 pb-12"><div className="rounded-[2rem] bg-slate-950 p-7 text-white md:p-10"><p className="font-bold text-indigo-300">NJACP Adaptive Study Companion</p><h1 className="mt-3 max-w-3xl text-4xl font-black md:text-6xl">A study plan that adapts when real life happens.</h1><p className="mt-4 max-w-2xl leading-7 text-slate-300">Use energy, available time and exam proximity to rebuild a realistic plan instead of punishing yourself for missing one.</p></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.4fr]"><div className="space-y-5"><div className="rounded-3xl border bg-white p-6 shadow-sm"><b>Today’s reality</b><label className="mt-5 block text-sm font-semibold">Energy: {energy}/10</label><input type="range" min="1" max="10" value={energy} onChange={e=>setEnergy(+e.target.value)} className="mt-3 w-full"/><label className="mt-5 block text-sm font-semibold">Available: {available} min</label><input type="range" min="15" max="240" step="15" value={available} onChange={e=>setAvailable(+e.target.value)} className="mt-3 w-full"/><label className="mt-5 block text-sm font-semibold">Exam: {examDays} days</label><input type="range" min="1" max="60" value={examDays} onChange={e=>setExamDays(+e.target.value)} className="mt-3 w-full"/><button onClick={adapt} disabled={loading} className="mt-6 w-full rounded-2xl bg-indigo-600 py-3 font-bold text-white">{loading?"Adapting…":"Adapt my plan"}</button><p className="mt-4 rounded-2xl bg-indigo-50 p-4 text-sm leading-6 text-indigo-900">{message}</p></div><div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex justify-between"><b>Progress</b><b className="text-indigo-600">{progress}%</b></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-indigo-600" style={{width:progress+"%"}}/></div><p className="mt-3 text-sm text-slate-500">{done} completed • {tasks.filter(t=>!t.done).reduce((n,t)=>n+t.minutes,0)} planned minutes remaining</p></div></div>
 <div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="font-black">Adaptive queue</div><div className="mt-5 space-y-3">{ordered.map(t=><button key={t.id} onClick={()=>toggle(t.id)} className={"flex w-full items-center gap-4 rounded-2xl border p-4 text-left "+(t.done?"bg-emerald-50":"hover:shadow-sm")}><span className="grid h-8 w-8 place-items-center rounded-full border font-black">{t.done?"✓":""}</span><span><b className={t.done?"line-through":""}>{t.subject} · {t.topic}</b><small className="mt-1 block text-slate-500">{t.minutes} min · {t.priority} priority</small></span></button>)}</div><form onSubmit={add} className="mt-5 grid gap-2 sm:grid-cols-[.7fr_1.3fr_auto]"><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject" className="rounded-xl bg-slate-100 px-3 py-3 text-sm"/><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Topic or task" className="rounded-xl bg-slate-100 px-3 py-3 text-sm"/><button className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Add</button></form></div></div></section></main>
}